<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <RootNamespace>BeatSaberAPI</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>BeatSaberAPI</Title>
    <RepositoryUrl>https://github.com/Hawkynt/BeatSaber-Playlist-Editor</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Hawkynt</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <PackageReference Include="FrameworkExtensions.Corlib" Version="1.0.2.480" />
    <PackageReference Include="FrameworkExtensions.System.Drawing" Version="1.0.0.36" />
  </ItemGroup>

</Project>
